# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Home page'
tagline:          'Home page'
description:      ''
url:              http://azhmogino.github.io

author:
  name:           'Andrey Zhmoginov'

paginate:         5
paginate_path:    "blog/page:num"
